<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class AmenitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Air Conditioning"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Clothes Dryer"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Fire extinguisher"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Hair Dryer"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Heating"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Laptop Friendly Workspace"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Self Check-in"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Washing Machine"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Bed Linens/Towels"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Contactless check-in and check out"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Fireplace"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Handicap Accessible"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Hot water"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Parking Included"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Smoke detector"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "WiFi Internet"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Carbon monoxide detector"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Elevator"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "First aid kit"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Hand sanitizer"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Ironing equipment"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Pets Considered"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Toys"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Cleaning and disinfection"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Essentials"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Full Equipped Kitchen"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Hangers"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Kids Friendly"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "Satellite Or Cable"]);
        DB::table('amenities')->insert(['category' => "Recommended",'title' => "TV"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Blender"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Dishwasher"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Ice maker"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Oven"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Wine glasses"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Bottled water"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Filtered Water"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Kettle"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Stove"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Cleaning products"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Freezer"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Kitchenette"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Toaster"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Coffee Maker"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Fridge"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Microwave"]);
        DB::table('amenities')->insert(['category' => "In the kitchen",'title' => "Water Cooler"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Accessible car park"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Boat dock"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Patio"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Private Parking"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Terrace"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Balcony"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Electric vehicle charger"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Paying parking off site"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Secured parking"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Jacuzzi"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "BBQ"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Garden"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Paying parking onsite"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Shared Parking"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Beach essentials"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Indoor parking"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Private entrance"]);
        DB::table('amenities')->insert(['category' => "Outside",'title' => "Street parking"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Fence around pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Infinity pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Private pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Heated Pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Outdoor pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Salt-water pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Indoor pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Outdoor pool seasonal"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Shallow end pool"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Indoor pool seasonal"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Pool cover"]);
        DB::table('amenities')->insert(['category' => "Pool",'title' => "Shared pool"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "24 hour arrival"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Breakfast Included"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Dvd Player"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Mosquito Net"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Stereo System"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Videogame Console"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Alarm clock"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Ceiling Fans"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Extra pillows and blankets"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Music library"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Streaming service"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Video Library"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Portable wifi"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Cellar"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Free Cleaning"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Professionally cleaned"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Telephone"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Wardrobe"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Books"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Central Heating"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Garage"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Room fan"]);
        DB::table('amenities')->insert(['category' => "Full comfort",'title' => "Vacuum cleaner"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Baby bath"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Changing table"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Game Room"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Kids' Games"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Table corner guards"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Baby crib"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Children's dinnerware"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Games For All Ages"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Kids Pool"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Travel cot"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Baby monitor"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Child's Swing"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Highchair"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Socket covers"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Video games"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Babysitter recommendation"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Fireplace guards"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Kids' Books"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Stair gates"]);
        DB::table('amenities')->insert(['category' => "Family",'title' => "Window guards"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Gated Community"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Masks available"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Smoking Forbidden"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Gated property"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Safe"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Social distancing"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Gloves available"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Safety card"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Staff wear protective equipment"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Locked bedroom(s)"]);
        DB::table('amenities')->insert(['category' => "Security And Safety",'title' => "Safety System"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Energy-efficient devices"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Organic food & beverages"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Sustainability projects support"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Information about property sustainability"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Paperless / recycled paper"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Sustainable materials"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "No single-use plastic"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Rainwater harvesting system"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Towel changed upon request"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "No single-use toiletries"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Renewable energy system"]);
        DB::table('amenities')->insert(['category' => "Sustainability",'title' => "Waste sorting"]);
    }
}
